### ISSUE TITLE
xx.g.dart error：type 'Data' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by android-dev2015** [nesprasit/Json2DartSerializable#1]
{
  "code": 0,
  "desc": "success",
  "data": {
    "uuid": "7acf6364-ea13-49ee-9c8a-63a231de2608",
    "username": "jklove",
  }
}

我使用上面的Json数据生成bean后，用toJson()方法拿到Map，在fromJson方法传入map进行互转，会报错。
After generating beans using the Json data above, I used the toJson() method to obtain the Map, and passed it into the FromJson method for mutual conversion, which resulted in an error.

var loginMap = login.toJson();
Login login2 = Login.fromJson(loginMap);

error：type 'Data' is not a subtype of type 'Map<String, dynamic>' in type cast

**Comment by nesprasit** [comment]
> { "code": 0, "desc": "success", "data": { "uuid": "7acf6364-ea13-49ee-9c8a-63a231de2608", "username": "jklove", } }
> 
> 我使用上面的Json数据生成bean后，用toJson()方法拿到Map，在fromJson方法传入map进行互转，会报错。 After generating beans using the Json data above, I used the toJson() method to obtain the Map, and passed it into the FromJson method for mutual conversion, which resulted in an error.
> 
> var loginMap = login.toJson(); Login login2 = Login.fromJson(loginMap);
> 
> error：type 'Data' is not a subtype of type 'Map<String, dynamic>' in type cast

you can also configure code generation by setting values in build.yaml

**Comment by nesprasit** [comment]
> { "code": 0, "desc": "success", "data": { "uuid": "7acf6364-ea13-49ee-9c8a-63a231de2608", "username": "jklove", } }
> 
> 我使用上面的Json数据生成bean后，用toJson()方法拿到Map，在fromJson方法传入map进行互转，会报错。 After generating beans using the Json data above, I used the toJson() method to obtain the Map, and passed it into the FromJson method for mutual conversion, which resulted in an error.
> 
> var loginMap = login.toJson(); Login login2 = Login.fromJson(loginMap);
> 
> error：type 'Data' is not a subtype of type 'Map<String, dynamic>' in type cast

you can also configure code generation by setting values in build.yaml. 
https://pub.dev/packages/json_serializable#build-configuration

simple code
```
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true <----- Add option
```

**Comment by android-dev2015** [comment]
> > { "code": 0, "desc": "success", "data": { "uuid": "7acf6364-ea13-49ee-9c8a-63a231de2608", "username": "jklove", } }
> > 我使用上面的Json数据生成bean后，用toJson()方法拿到Map，在fromJson方法传入map进行互转，会报错。 After generating beans using the Json data above, I used the toJson() method to obtain the Map, and passed it into the FromJson method for mutual conversion, which resulted in an error.
> > var loginMap = login.toJson(); Login login2 = Login.fromJson(loginMap);
> > error：type 'Data' is not a subtype of type 'Map<String, dynamic>' in type cast
> 
> you can also configure code generation by setting values in build.yaml. https://pub.dev/packages/json_serializable#build-configuration
> 
> simple code
> 
> ```
> targets:
>   $default:
>     builders:
>       json_serializable:
>         options:
>           explicit_to_json: true <----- Add option
> ```

thank you, it's ok
